In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("C:/Users/lenovo/Desktop/final_project/Stroke Prediction Dataset.csv")
df

,Sex,BMI,Smoking,AlcoholDrinking,HeartDisease,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,Stroke
0,Female,16.60,Yes,No,No,3,30,No,Yes,55-59,White,Yes,Very good,5,Yes,No,No
1,Female,20.34,No,No,No,0,0,No,No,80 or older,White,Yes,Very good,7,No,No,Yes
2,Male,26.58,Yes,No,No,20,30,No,Yes,65-69,White,Yes,Fair,8,Yes,No,No
3,Female,24.21,No,No,No,0,0,No,No,75-79,White,No,Good,6,No,No,No
4,Female,23.71,No,No,No,28,0,Yes,No,40-44,White,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Male,27.41,Yes,No,Yes,7,0,Yes,Yes,60-64,Hispanic,No,Fair,6,Yes,No,No
319791,Male,29.84,Yes,No,No,0,0,No,No,35-39,Hispanic,Yes,Very good,5,Yes,No,No
319792,Female,24.24,No,No,No,0,0,No,No,45-49,Hispanic,Yes,Good,6,No,No,No
319793,Female,32.81,No,No,No,0,0,No,No,25-29,Hispanic,No,Good,12,No,No,No
319794,Female,46.56,No,No,No,0,0,No,No,80 or older,Hispanic,Yes,Good,8,No,No,No

In [3]:
df.isnull().sum()

Sex                 0
BMI                 0
Smoking             0
AlcoholDrinking     0
HeartDisease        0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Diabetic            0
AgeCategory         0
Race                0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
Stroke              0
dtype: int64

In [4]:
df=df.dropna()

In [5]:
df

,Sex,BMI,Smoking,AlcoholDrinking,HeartDisease,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,Stroke
0,Female,16.60,Yes,No,No,3,30,No,Yes,55-59,White,Yes,Very good,5,Yes,No,No
1,Female,20.34,No,No,No,0,0,No,No,80 or older,White,Yes,Very good,7,No,No,Yes
2,Male,26.58,Yes,No,No,20,30,No,Yes,65-69,White,Yes,Fair,8,Yes,No,No
3,Female,24.21,No,No,No,0,0,No,No,75-79,White,No,Good,6,No,No,No
4,Female,23.71,No,No,No,28,0,Yes,No,40-44,White,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Male,27.41,Yes,No,Yes,7,0,Yes,Yes,60-64,Hispanic,No,Fair,6,Yes,No,No
319791,Male,29.84,Yes,No,No,0,0,No,No,35-39,Hispanic,Yes,Very good,5,Yes,No,No
319792,Female,24.24,No,No,No,0,0,No,No,45-49,Hispanic,Yes,Good,6,No,No,No
319793,Female,32.81,No,No,No,0,0,No,No,25-29,Hispanic,No,Good,12,No,No,No
319794,Female,46.56,No,No,No,0,0,No,No,80 or older,Hispanic,Yes,Good,8,No,No,No

In [6]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Sex               319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   HeartDisease      319795 non-null  object
 5   PhysicalHealth    319795 non-null  int64
 6   MentalHealth      319795 non-null  int64
 7   DiffWalking       319795 non-null  object
 8   Diabetic          319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  PhysicalActivity  319795 non-null  object
 12  GenHealth         319795 non-null  object
 13  SleepTime         319795 non-null  int64
 14  Asthma            319795 non-null  object
 15  KidneyDisease     319795 non-null  object
 16  Stroke            319795 non-null  object
dtypes: float64(1), int64(3), object(13)
memory usage: 41.5+ MB

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  319795.000000    319795.00000  319795.000000  319795.000000
mean       28.325399         3.37171       3.898366       7.097075
std         6.356100         7.95085       7.955235       1.436007
min        12.020000         0.00000       0.000000       1.000000
25%        24.030000         0.00000       0.000000       6.000000
50%        27.340000         0.00000       0.000000       7.000000
75%        31.420000         2.00000       3.000000       8.000000
max        94.850000        30.00000      30.000000      24.000000

In [7]:
df.drop(columns=['Race'], inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])

In [9]:
df

,Sex,BMI,Smoking,AlcoholDrinking,HeartDisease,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,AgeCategory,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,Stroke
0,0,16.60,1,0,0,3,30,0,2,7,1,4,5,1,0,0
1,0,20.34,0,0,0,0,0,0,0,12,1,4,7,0,0,1
2,1,26.58,1,0,0,20,30,0,2,9,1,1,8,1,0,0
3,0,24.21,0,0,0,0,0,0,0,11,0,2,6,0,0,0
4,0,23.71,0,0,0,28,0,1,0,4,1,4,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,1,7,0,1,2,8,0,1,6,1,0,0
319791,1,29.84,1,0,0,0,0,0,0,3,1,4,5,1,0,0
319792,0,24.24,0,0,0,0,0,0,0,5,1,2,6,0,0,0
319793,0,32.81,0,0,0,0,0,0,0,1,0,2,12,0,0,0
319794,0,46.56,0,0,0,0,0,0,0,12,1,2,8,0,0,0

In [10]:
df.describe()

,Sex,BMI,Smoking,AlcoholDrinking,HeartDisease,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,AgeCategory,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,Stroke
count,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.00000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000
mean,0.475273,28.325399,0.412477,0.068097,0.085595,3.37171,3.898366,0.138870,0.300386,6.514536,0.775362,2.220904,7.097075,0.134061,0.036833,0.037740
std,0.499389,6.356100,0.492281,0.251912,0.279766,7.95085,7.955235,0.345812,0.716480,3.564759,0.417344,1.534647,1.436007,0.340718,0.188352,0.190567
min,0.000000,12.020000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,24.030000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000,6.000000,0.000000,0.000000,0.000000
50%,0.000000,27.340000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,7.000000,1.000000,2.000000,7.000000,0.000000,0.000000,0.000000
75%,1.000000,31.420000,1.000000,0.000000,0.000000,2.00000,3.000000,0.000000,0.000000,9.000000,1.000000,4.000000,8.000000,0.000000,0.000000,0.000000
max,1.000000,94.850000,1.000000,1.000000,1.000000,30.00000,30.000000,1.000000,3.000000,12.000000,1.000000,4.000000,24.000000,1.000000,1.000000,1.000000

In [11]:
num_cols = ['BMI']
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    
    df[col] = np.clip(df[col], lower, upper)

In [12]:
df.describe()

,Sex,BMI,Smoking,AlcoholDrinking,HeartDisease,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,AgeCategory,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,Stroke
count,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.00000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000
mean,0.475273,28.149585,0.412477,0.068097,0.085595,3.37171,3.898366,0.138870,0.300386,6.514536,0.775362,2.220904,7.097075,0.134061,0.036833,0.037740
std,0.499389,5.767529,0.492281,0.251912,0.279766,7.95085,7.955235,0.345812,0.716480,3.564759,0.417344,1.534647,1.436007,0.340718,0.188352,0.190567
min,0.000000,12.945000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,24.030000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000,6.000000,0.000000,0.000000,0.000000
50%,0.000000,27.340000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,7.000000,1.000000,2.000000,7.000000,0.000000,0.000000,0.000000
75%,1.000000,31.420000,1.000000,0.000000,0.000000,2.00000,3.000000,0.000000,0.000000,9.000000,1.000000,4.000000,8.000000,0.000000,0.000000,0.000000
max,1.000000,42.505000,1.000000,1.000000,1.000000,30.00000,30.000000,1.000000,3.000000,12.000000,1.000000,4.000000,24.000000,1.000000,1.000000,1.000000

In [13]:
df['Stroke'].value_counts()

Stroke
0    307726
1     12069
Name: count, dtype: int64

In [14]:
from imblearn.under_sampling import RandomUnderSampler

# تحديد X و y
X = df.drop("Stroke", axis=1)
y = df["Stroke"]

# عمل undersampling
rus = RandomUnderSampler(random_state=42)
X, y = rus.fit_resample(X, y)

# نشوف التوزيع الجديد
print(y.value_counts())

Stroke
0    12069
1    12069
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1767  629]
 [ 584 1848]]
              precision    recall  f1-score   support

           0       0.75      0.74      0.74      2396
           1       0.75      0.76      0.75      2432

    accuracy                           0.75      4828
   macro avg       0.75      0.75      0.75      4828
weighted avg       0.75      0.75      0.75      4828

In [17]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1733  663]
 [ 533 1899]]
              precision    recall  f1-score   support

           0       0.76      0.72      0.74      2396
           1       0.74      0.78      0.76      2432

    accuracy                           0.75      4828
   macro avg       0.75      0.75      0.75      4828
weighted avg       0.75      0.75      0.75      4828

In [18]:
models = {
    "XGB": xgb,
    "RandomForest": rf,    
}

for name, mdl in models.items():
    y_pred = mdl.predict(X_test)
    print("\n",name)
    print(classification_report(y_test, y_pred))

 XGB
              precision    recall  f1-score   support

           0       0.76      0.72      0.74      2396
           1       0.74      0.78      0.76      2432

    accuracy                           0.75      4828
   macro avg       0.75      0.75      0.75      4828
weighted avg       0.75      0.75      0.75      4828


 RandomForest
              precision    recall  f1-score   support

           0       0.75      0.74      0.74      2396
           1       0.75      0.76      0.75      2432

    accuracy                           0.75      4828
   macro avg       0.75      0.75      0.75      4828
weighted avg       0.75      0.75      0.75      4828

In [19]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

params = {
    'max_depth':[3,5,7],
    'learning_rate':[0.01,0.05,0.1],
    'n_estimators':[300,500],
    'subsample':[0.8,1],
    'colsample_bytree':[0.8,1]
}

grid = GridSearchCV(
    XGBClassifier(eval_metric="logloss"),
    params,
    scoring="accuracy",
    cv=3,
    n_jobs=-1
)

grid.fit(X_train, y_train)

print(grid.best_params_)

{'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 300, 'subsample': 0.8}

In [20]:
# بعد GridSearch
best_xgb = grid.best_estimator_

from sklearn.metrics import roc_curve, classification_report

y_prob = best_xgb.predict_proba(X_test)[:,1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# أفضل threshold
optimal_idx = (tpr - fpr).argmax()
best_threshold = thresholds[optimal_idx]

print("Best Threshold:", best_threshold)

y_pred_opt = (y_prob > best_threshold).astype(int)
print(classification_report(y_test, y_pred_opt))

Best Threshold: 0.4846692
              precision    recall  f1-score   support

           0       0.77      0.72      0.75      2396
           1       0.74      0.79      0.77      2432

    accuracy                           0.76      4828
   macro avg       0.76      0.76      0.76      4828
weighted avg       0.76      0.76      0.76      4828

In [21]:
import pandas as pd

sample = pd.DataFrame({
    "Sex":[1,0,1,0,1,0,1,0],
    "BMI":[34.5,22.3,41.8,26.0,30.4,19.5,37.2,24.8],
    "Smoking":[1,0,1,0,1,0,1,0],
    "AlcoholDrinking":[0,0,1,0,0,0,1,0],
    "HeartDisease":[1,0,1,0,1,0,1,0],
    "PhysicalHealth":[12,0,20,2,7,0,25,1],
    "MentalHealth":[8,1,15,0,5,0,20,0],
    "DiffWalking":[1,0,1,0,1,0,1,0],
    "Diabetic":[1,0,2,0,1,0,3,0],
    "AgeCategory":[10,3,11,5,8,2,12,4],
    "PhysicalActivity":[0,1,0,1,0,1,0,1],
    "GenHealth":[4,1,4,2,3,1,4,2],
    "SleepTime":[5,8,4,7,6,9,3,7],
    "Asthma":[0,0,1,0,0,0,1,0],
    "KidneyDisease":[0,0,1,0,0,0,1,0]
})

pred = best_xgb.predict(sample)
print(pred)

[1 0 1 0 1 0 1 0]

In [22]:
from sklearn.metrics import accuracy_score, classification_report

# توقعات التدريب
train_pred = best_xgb.predict(X_train)
test_pred  = best_xgb.predict(X_test)

print("=== TRAIN ===")
print(accuracy_score(y_train, train_pred))
print(classification_report(y_train, train_pred))

print("\n=== TEST ===")
print(accuracy_score(y_test, test_pred))
print(classification_report(y_test, test_pred))

=== TRAIN ===
0.7601760745727603
              precision    recall  f1-score   support

           0       0.77      0.74      0.76      9673
           1       0.75      0.78      0.76      9637

    accuracy                           0.76     19310
   macro avg       0.76      0.76      0.76     19310
weighted avg       0.76      0.76      0.76     19310


=== TEST ===
0.7568351284175642
              precision    recall  f1-score   support

           0       0.77      0.73      0.75      2396
           1       0.75      0.78      0.76      2432

    accuracy                           0.76      4828
   macro avg       0.76      0.76      0.76      4828
weighted avg       0.76      0.76      0.76      4828

In [23]:
# import pickle

# # حفظ الموديل
# with open("stroke_model.pkl", "wb") as f:
#     pickle.dump(best_xgb, f)

# print("✅ Model saved successfully!")

✅ Model saved successfully!