In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("C:/Users/lenovo/Desktop/final_project/sickrightfoot/sickfoot.csv")
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1,09:35:32,2014-02-05,23.665153,23.670404,23.798297,24.064021,23.860387,23.166001,24.453311,23.809233,23.084740,93.337682,103.830583,165.839884,131.216472,141.792939,103.714719,176.566740,151.150779
1,2,09:35:52,2014-02-05,23.677651,23.698930,23.837383,24.097838,23.885617,23.181379,24.513571,23.842472,23.115352,76.512637,103.046557,168.813242,133.087164,146.415524,102.775794,178.830630,153.250787
2,3,09:36:12,2014-02-05,23.690148,23.727457,23.876470,24.131656,23.910847,23.196756,24.573830,23.875711,23.145964,59.687592,102.262532,171.786599,134.957856,151.038109,101.836870,181.094520,155.350795
3,4,09:36:32,2014-02-05,23.703697,23.756147,23.914859,24.165223,23.935938,23.212191,24.630898,23.907588,23.174277,44.048767,101.476076,174.626373,136.696587,155.507469,100.900611,183.307349,157.149321
4,5,09:36:52,2014-02-05,23.717247,23.784837,23.953249,24.198790,23.961030,23.227626,24.687967,23.939466,23.202591,28.409943,100.689620,177.466146,138.435318,159.976829,99.964353,185.520178,158.947848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29103,1908,2016-01-27 17:26:37,2016-01-27,29.025204,29.197961,29.288674,229.115416,29.536581,30.165898,29.925653,31.537212,25.772944,3832.604332,3936.114152,3930.022798,0.000000,3877.463467,3972.292391,3508.361984,3350.071287
29104,1909,2016-01-27 17:26:40,2016-01-27,29.023124,29.196185,29.285040,229.338156,29.532473,30.163200,29.924333,31.537116,25.772566,3832.160606,3935.886786,3929.420990,0.000000,3876.942225,3972.121873,3505.688899,3349.061347
29105,1910,2016-01-27 17:26:43,2016-01-27,29.021044,29.194410,29.281405,229.560896,29.528365,30.160502,29.923013,31.537019,25.772188,3831.716880,3935.659419,3928.819183,0.000000,3876.420982,3971.951355,3503.015814,3348.051407
29106,1911,2016-01-27 17:26:46,2016-01-27,29.018964,29.192634,29.277771,229.783636,29.524257,30.157805,29.921693,31.536922,25.771810,3831.273154,3935.432052,3928.217375,0.000000,3875.899739,3971.780836,3500.342730,3347.041468
29107,1912,2016-01-27 17:26:49,2016-01-27,29.016884,29.190859,29.274137,230.006377,29.520149,30.155107,29.920373,31.536826,25.771432,3830.829428,3935.204686,3927.615567,0.000000,3875.378497,3971.610318,3497.669645,3346.031528

In [3]:
print(df.shape)
df = df.drop_duplicates()
print(df.shape)

(29108, 20)
(29108, 20)

In [4]:
print("Missing values :")
print(df.isnull().sum())

Missing values :
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
dtype: int64

In [5]:
df.drop(columns=['0'], inplace=True)
df.drop(columns=['1'], inplace=True)
df.drop(columns=['2'], inplace=True)
df.drop(columns=['11'], inplace=True)

In [6]:
df

,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19
0,23.665153,23.670404,23.798297,24.064021,23.860387,23.166001,24.453311,23.809233,93.337682,103.830583,165.839884,131.216472,141.792939,103.714719,176.566740,151.150779
1,23.677651,23.698930,23.837383,24.097838,23.885617,23.181379,24.513571,23.842472,76.512637,103.046557,168.813242,133.087164,146.415524,102.775794,178.830630,153.250787
2,23.690148,23.727457,23.876470,24.131656,23.910847,23.196756,24.573830,23.875711,59.687592,102.262532,171.786599,134.957856,151.038109,101.836870,181.094520,155.350795
3,23.703697,23.756147,23.914859,24.165223,23.935938,23.212191,24.630898,23.907588,44.048767,101.476076,174.626373,136.696587,155.507469,100.900611,183.307349,157.149321
4,23.717247,23.784837,23.953249,24.198790,23.961030,23.227626,24.687967,23.939466,28.409943,100.689620,177.466146,138.435318,159.976829,99.964353,185.520178,158.947848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29103,29.025204,29.197961,29.288674,229.115416,29.536581,30.165898,29.925653,31.537212,3832.604332,3936.114152,3930.022798,0.000000,3877.463467,3972.292391,3508.361984,3350.071287
29104,29.023124,29.196185,29.285040,229.338156,29.532473,30.163200,29.924333,31.537116,3832.160606,3935.886786,3929.420990,0.000000,3876.942225,3972.121873,3505.688899,3349.061347
29105,29.021044,29.194410,29.281405,229.560896,29.528365,30.160502,29.923013,31.537019,3831.716880,3935.659419,3928.819183,0.000000,3876.420982,3971.951355,3503.015814,3348.051407
29106,29.018964,29.192634,29.277771,229.783636,29.524257,30.157805,29.921693,31.536922,3831.273154,3935.432052,3928.217375,0.000000,3875.899739,3971.780836,3500.342730,3347.041468
29107,29.016884,29.190859,29.274137,230.006377,29.520149,30.155107,29.920373,31.536826,3830.829428,3935.204686,3927.615567,0.000000,3875.378497,3971.610318,3497.669645,3346.031528

In [7]:
new_names = ["Temp1", "Temp2", "Temp3", "Temp4", "Temp5"]

for i in range(5):
    df.rename(columns={df.columns[i]: new_names[i]}, inplace=True)


df.rename(columns={'8': 'BigF_T'}, inplace=True)
df.rename(columns={'9': 'Side_T'}, inplace=True)
df.rename(columns={'10': 'Center_T'}, inplace=True)
df.head()

,Temp1,Temp2,Temp3,Temp4,Temp5,BigF_T,Side_T,Center_T,12,13,14,15,16,17,18,19
0,23.665153,23.670404,23.798297,24.064021,23.860387,23.166001,24.453311,23.809233,93.337682,103.830583,165.839884,131.216472,141.792939,103.714719,176.566740,151.150779
1,23.677651,23.698930,23.837383,24.097838,23.885617,23.181379,24.513571,23.842472,76.512637,103.046557,168.813242,133.087164,146.415524,102.775794,178.830630,153.250787
2,23.690148,23.727457,23.876470,24.131656,23.910847,23.196756,24.573830,23.875711,59.687592,102.262532,171.786599,134.957856,151.038109,101.836870,181.094520,155.350795
3,23.703697,23.756147,23.914859,24.165223,23.935938,23.212191,24.630898,23.907588,44.048767,101.476076,174.626373,136.696587,155.507469,100.900611,183.307349,157.149321
4,23.717247,23.784837,23.953249,24.198790,23.961030,23.227626,24.687967,23.939466,28.409943,100.689620,177.466146,138.435318,159.976829,99.964353,185.520178,158.947848

In [8]:
new_names = ["Pres1", "Pres2", "Pres3", "Pres4", "Pres5"]

start_col = 8  

for i in range(5):
    df.rename(columns={df.columns[start_col + i]: new_names[i]}, inplace=True)


df.rename(columns={'17': 'BigF_P'}, inplace=True)
df.rename(columns={'18': 'Side_P'}, inplace=True)
df.rename(columns={'19': 'Center_P'}, inplace=True)
df.head()

,Temp1,Temp2,Temp3,Temp4,Temp5,BigF_T,Side_T,Center_T,Pres1,Pres2,Pres3,Pres4,Pres5,BigF_P,Side_P,Center_P
0,23.665153,23.670404,23.798297,24.064021,23.860387,23.166001,24.453311,23.809233,93.337682,103.830583,165.839884,131.216472,141.792939,103.714719,176.566740,151.150779
1,23.677651,23.698930,23.837383,24.097838,23.885617,23.181379,24.513571,23.842472,76.512637,103.046557,168.813242,133.087164,146.415524,102.775794,178.830630,153.250787
2,23.690148,23.727457,23.876470,24.131656,23.910847,23.196756,24.573830,23.875711,59.687592,102.262532,171.786599,134.957856,151.038109,101.836870,181.094520,155.350795
3,23.703697,23.756147,23.914859,24.165223,23.935938,23.212191,24.630898,23.907588,44.048767,101.476076,174.626373,136.696587,155.507469,100.900611,183.307349,157.149321
4,23.717247,23.784837,23.953249,24.198790,23.961030,23.227626,24.687967,23.939466,28.409943,100.689620,177.466146,138.435318,159.976829,99.964353,185.520178,158.947848

In [9]:
df['Label']=1

In [10]:
df

,Temp1,Temp2,Temp3,Temp4,Temp5,BigF_T,Side_T,Center_T,Pres1,Pres2,Pres3,Pres4,Pres5,BigF_P,Side_P,Center_P,Label
0,23.665153,23.670404,23.798297,24.064021,23.860387,23.166001,24.453311,23.809233,93.337682,103.830583,165.839884,131.216472,141.792939,103.714719,176.566740,151.150779,1
1,23.677651,23.698930,23.837383,24.097838,23.885617,23.181379,24.513571,23.842472,76.512637,103.046557,168.813242,133.087164,146.415524,102.775794,178.830630,153.250787,1
2,23.690148,23.727457,23.876470,24.131656,23.910847,23.196756,24.573830,23.875711,59.687592,102.262532,171.786599,134.957856,151.038109,101.836870,181.094520,155.350795,1
3,23.703697,23.756147,23.914859,24.165223,23.935938,23.212191,24.630898,23.907588,44.048767,101.476076,174.626373,136.696587,155.507469,100.900611,183.307349,157.149321,1
4,23.717247,23.784837,23.953249,24.198790,23.961030,23.227626,24.687967,23.939466,28.409943,100.689620,177.466146,138.435318,159.976829,99.964353,185.520178,158.947848,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29103,29.025204,29.197961,29.288674,229.115416,29.536581,30.165898,29.925653,31.537212,3832.604332,3936.114152,3930.022798,0.000000,3877.463467,3972.292391,3508.361984,3350.071287,1
29104,29.023124,29.196185,29.285040,229.338156,29.532473,30.163200,29.924333,31.537116,3832.160606,3935.886786,3929.420990,0.000000,3876.942225,3972.121873,3505.688899,3349.061347,1
29105,29.021044,29.194410,29.281405,229.560896,29.528365,30.160502,29.923013,31.537019,3831.716880,3935.659419,3928.819183,0.000000,3876.420982,3971.951355,3503.015814,3348.051407,1
29106,29.018964,29.192634,29.277771,229.783636,29.524257,30.157805,29.921693,31.536922,3831.273154,3935.432052,3928.217375,0.000000,3875.899739,3971.780836,3500.342730,3347.041468,1
29107,29.016884,29.190859,29.274137,230.006377,29.520149,30.155107,29.920373,31.536826,3830.829428,3935.204686,3927.615567,0.000000,3875.378497,3971.610318,3497.669645,3346.031528,1

In [11]:
df = df[df >= 0].dropna()

In [12]:
df

,Temp1,Temp2,Temp3,Temp4,Temp5,BigF_T,Side_T,Center_T,Pres1,Pres2,Pres3,Pres4,Pres5,BigF_P,Side_P,Center_P,Label
0,23.665153,23.670404,23.798297,24.064021,23.860387,23.166001,24.453311,23.809233,93.337682,103.830583,165.839884,131.216472,141.792939,103.714719,176.566740,151.150779,1
1,23.677651,23.698930,23.837383,24.097838,23.885617,23.181379,24.513571,23.842472,76.512637,103.046557,168.813242,133.087164,146.415524,102.775794,178.830630,153.250787,1
2,23.690148,23.727457,23.876470,24.131656,23.910847,23.196756,24.573830,23.875711,59.687592,102.262532,171.786599,134.957856,151.038109,101.836870,181.094520,155.350795,1
3,23.703697,23.756147,23.914859,24.165223,23.935938,23.212191,24.630898,23.907588,44.048767,101.476076,174.626373,136.696587,155.507469,100.900611,183.307349,157.149321,1
4,23.717247,23.784837,23.953249,24.198790,23.961030,23.227626,24.687967,23.939466,28.409943,100.689620,177.466146,138.435318,159.976829,99.964353,185.520178,158.947848,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29103,29.025204,29.197961,29.288674,229.115416,29.536581,30.165898,29.925653,31.537212,3832.604332,3936.114152,3930.022798,0.000000,3877.463467,3972.292391,3508.361984,3350.071287,1
29104,29.023124,29.196185,29.285040,229.338156,29.532473,30.163200,29.924333,31.537116,3832.160606,3935.886786,3929.420990,0.000000,3876.942225,3972.121873,3505.688899,3349.061347,1
29105,29.021044,29.194410,29.281405,229.560896,29.528365,30.160502,29.923013,31.537019,3831.716880,3935.659419,3928.819183,0.000000,3876.420982,3971.951355,3503.015814,3348.051407,1
29106,29.018964,29.192634,29.277771,229.783636,29.524257,30.157805,29.921693,31.536922,3831.273154,3935.432052,3928.217375,0.000000,3875.899739,3971.780836,3500.342730,3347.041468,1
29107,29.016884,29.190859,29.274137,230.006377,29.520149,30.155107,29.920373,31.536826,3830.829428,3935.204686,3927.615567,0.000000,3875.378497,3971.610318,3497.669645,3346.031528,1

In [13]:
df.drop(columns=['Temp1'], inplace=True)
df.drop(columns=['Temp3'], inplace=True)
df.drop(columns=['Temp4'], inplace=True)
df.drop(columns=['Pres1'], inplace=True)
df.drop(columns=['Pres3'], inplace=True)
df.drop(columns=['Pres4'], inplace=True)

In [14]:
df

,Temp2,Temp5,BigF_T,Side_T,Center_T,Pres2,Pres5,BigF_P,Side_P,Center_P,Label
0,23.670404,23.860387,23.166001,24.453311,23.809233,103.830583,141.792939,103.714719,176.566740,151.150779,1
1,23.698930,23.885617,23.181379,24.513571,23.842472,103.046557,146.415524,102.775794,178.830630,153.250787,1
2,23.727457,23.910847,23.196756,24.573830,23.875711,102.262532,151.038109,101.836870,181.094520,155.350795,1
3,23.756147,23.935938,23.212191,24.630898,23.907588,101.476076,155.507469,100.900611,183.307349,157.149321,1
4,23.784837,23.961030,23.227626,24.687967,23.939466,100.689620,159.976829,99.964353,185.520178,158.947848,1
...,...,...,...,...,...,...,...,...,...,...,...
29103,29.197961,29.536581,30.165898,29.925653,31.537212,3936.114152,3877.463467,3972.292391,3508.361984,3350.071287,1
29104,29.196185,29.532473,30.163200,29.924333,31.537116,3935.886786,3876.942225,3972.121873,3505.688899,3349.061347,1
29105,29.194410,29.528365,30.160502,29.923013,31.537019,3935.659419,3876.420982,3971.951355,3503.015814,3348.051407,1
29106,29.192634,29.524257,30.157805,29.921693,31.536922,3935.432052,3875.899739,3971.780836,3500.342730,3347.041468,1
29107,29.190859,29.520149,30.155107,29.920373,31.536826,3935.204686,3875.378497,3971.610318,3497.669645,3346.031528,1

In [15]:
df.rename(columns={'Temp2': 'Temp1'}, inplace=True)
df.rename(columns={'Temp5': 'Temp2'}, inplace=True)
df.rename(columns={'Pres2': 'Pres1'}, inplace=True)
df.rename(columns={'Pres5': 'Pres2'}, inplace=True)

In [16]:
df

,Temp1,Temp2,BigF_T,Side_T,Center_T,Pres1,Pres2,BigF_P,Side_P,Center_P,Label
0,23.670404,23.860387,23.166001,24.453311,23.809233,103.830583,141.792939,103.714719,176.566740,151.150779,1
1,23.698930,23.885617,23.181379,24.513571,23.842472,103.046557,146.415524,102.775794,178.830630,153.250787,1
2,23.727457,23.910847,23.196756,24.573830,23.875711,102.262532,151.038109,101.836870,181.094520,155.350795,1
3,23.756147,23.935938,23.212191,24.630898,23.907588,101.476076,155.507469,100.900611,183.307349,157.149321,1
4,23.784837,23.961030,23.227626,24.687967,23.939466,100.689620,159.976829,99.964353,185.520178,158.947848,1
...,...,...,...,...,...,...,...,...,...,...,...
29103,29.197961,29.536581,30.165898,29.925653,31.537212,3936.114152,3877.463467,3972.292391,3508.361984,3350.071287,1
29104,29.196185,29.532473,30.163200,29.924333,31.537116,3935.886786,3876.942225,3972.121873,3505.688899,3349.061347,1
29105,29.194410,29.528365,30.160502,29.923013,31.537019,3935.659419,3876.420982,3971.951355,3503.015814,3348.051407,1
29106,29.192634,29.524257,30.157805,29.921693,31.536922,3935.432052,3875.899739,3971.780836,3500.342730,3347.041468,1
29107,29.190859,29.520149,30.155107,29.920373,31.536826,3935.204686,3875.378497,3971.610318,3497.669645,3346.031528,1

In [17]:
(df < 0).sum()

Temp1       0
Temp2       0
BigF_T      0
Side_T      0
Center_T    0
Pres1       0
Pres2       0
BigF_P      0
Side_P      0
Center_P    0
Label       0
dtype: int64

In [18]:
pressure_cols = ['BigF_P','Center_P','Side_P','Pres1','Pres2']
df = df[(df[pressure_cols] <= 4095).all(axis=1)].reset_index(drop=True)

In [19]:
temp_cols = ['BigF_T','Center_T','Side_T','Temp1','Temp2']
df = df[(df[temp_cols] >= 20).all(axis=1) & (df[temp_cols] <= 40).all(axis=1)].reset_index(drop=True)

In [20]:
df[pressure_cols] = df[pressure_cols].clip(lower=0, upper=4095)
df[temp_cols] = df[temp_cols].clip(lower=20, upper=40)

In [21]:
df

,Temp1,Temp2,BigF_T,Side_T,Center_T,Pres1,Pres2,BigF_P,Side_P,Center_P,Label
0,23.670404,23.860387,23.166001,24.453311,23.809233,103.830583,141.792939,103.714719,176.566740,151.150779,1
1,23.698930,23.885617,23.181379,24.513571,23.842472,103.046557,146.415524,102.775794,178.830630,153.250787,1
2,23.727457,23.910847,23.196756,24.573830,23.875711,102.262532,151.038109,101.836870,181.094520,155.350795,1
3,23.756147,23.935938,23.212191,24.630898,23.907588,101.476076,155.507469,100.900611,183.307349,157.149321,1
4,23.784837,23.961030,23.227626,24.687967,23.939466,100.689620,159.976829,99.964353,185.520178,158.947848,1
...,...,...,...,...,...,...,...,...,...,...,...
16224,29.197961,29.536581,30.165898,29.925653,31.537212,3936.114152,3877.463467,3972.292391,3508.361984,3350.071287,1
16225,29.196185,29.532473,30.163200,29.924333,31.537116,3935.886786,3876.942225,3972.121873,3505.688899,3349.061347,1
16226,29.194410,29.528365,30.160502,29.923013,31.537019,3935.659419,3876.420982,3971.951355,3503.015814,3348.051407,1
16227,29.192634,29.524257,30.157805,29.921693,31.536922,3935.432052,3875.899739,3971.780836,3500.342730,3347.041468,1
16228,29.190859,29.520149,30.155107,29.920373,31.536826,3935.204686,3875.378497,3971.610318,3497.669645,3346.031528,1

In [22]:
df_sick = df.copy()    # داتا المرضى فقط (انت شغال عليها أصلاً)

target_size = 25000
current_size = len(df_sick)

extra_needed = target_size - current_size

print("Current sick rows:", current_size)
print("Extra needed:", extra_needed)

def add_noise(df, std_factor=0.015):
    noisy = df.copy()
    for col in df.columns:
        if col != "Label":
            noise = np.random.normal(0, df[col].std() * std_factor, size=len(df))
            noisy[col] = df[col] + noise
    return noisy

if extra_needed > 0:
    # نخليها random sample بس هنعمل عليها Noise عشان تبقى جديدة
    new_rows_raw = df_sick.sample(extra_needed, replace=True, random_state=42)
    new_rows = add_noise(new_rows_raw)
    
    df = pd.concat([df_sick, new_rows], ignore_index=True)
else:
    df = df_sick.sample(target_size, random_state=42)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Final sick rows:", len(df))
print("Duplicated rows:", df.duplicated().sum())

Current sick rows: 16229
Extra needed: 8771
Final sick rows: 25000
Duplicated rows: 0

In [23]:
df

,Temp1,Temp2,BigF_T,Side_T,Center_T,Pres1,Pres2,BigF_P,Side_P,Center_P,Label
0,28.561701,27.570591,26.284619,27.299837,28.482244,3201.967747,4002.382255,1232.438178,3723.591919,1284.953117,1
1,29.815007,30.770661,30.770811,30.597531,31.751040,3980.409962,3906.203255,3967.847567,3667.655598,3118.086150,1
2,30.218279,31.146319,24.016086,29.765228,30.530594,2145.762685,3516.820912,0.000000,1199.600155,0.000000,1
3,27.693219,29.349521,26.092417,29.670568,32.216132,3794.760520,3923.428016,3402.132228,3901.521387,3977.483507,1
4,27.341423,29.061602,25.755129,29.624113,32.527953,3762.810060,3943.956711,3449.797945,3918.557762,3906.357397,1
...,...,...,...,...,...,...,...,...,...,...,...
24995,22.808923,24.405923,22.315182,24.603855,25.737175,3793.207471,3972.553112,3469.468845,3955.315748,3721.916345,1
24996,27.037650,26.336795,24.154661,27.633349,27.533159,2490.755765,2604.769034,2178.603151,3768.189116,0.000000,1
24997,31.199369,30.993360,30.503644,31.568145,30.500509,191.008318,207.306289,160.155721,202.627575,348.043492,1
24998,30.310123,31.104695,30.979659,30.946162,31.763029,3481.333091,632.526367,3671.824596,0.000000,35.344326,1
24999,29.985326,30.830602,30.905909,30.726735,31.852574,3951.984076,3906.986653,3938.707155,3778.409524,3633.966257,1

In [24]:
print("Duplicated rows:", df.duplicated().sum())

Duplicated rows: 0

In [25]:
#df.to_csv("final_sick.csv", index=False)